# Secploy Configuration Example
# Place this file as .secploy in your project root or specify path using config_file parameter

# Required Settings
# -----------------
api_key: your-api-key # Your Secploy API key from the dashboard
organization_id: your-organization-id # Your Secploy Organization ID from the dashboard
ingest_url: https://api.secploy.com # Secploy ingestion endpoint
environment: production # Environment name (e.g., production, staging, development)

# Event Processing
# ---------------
batch_size: 100 # Maximum number of events to batch before sending
flush_interval: 30 # Maximum time (seconds) to hold events before sending
max_queue_size: 5000 # Maximum number of events to keep in memory

# Performance Settings
# ------------------
sampling_rate: 0.1 # Percentage of events to sample (0.1 = 10%)
max_retry: 3 # Maximum number of retry attempts for failed requests
retry_attempts: 2 # Number of retries for transient failures

# Monitoring
# ---------
heartbeat_interval: 60 # Interval (seconds) between heartbeat signals
source_root: /app # Root directory of your application

# Debug Options
# ------------
debug: false # Enable detailed debug logging
log_level: INFO # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
ignore_errors: false # Continue processing on non-critical errors

# Notes:
# 1. All time values are in seconds
# 2. Place this file in your project root as '.secploy'
# 3. You can override any setting using the SecployConfig object
# 4. Environment-specific configurations can be placed in .secploy.{env} files
